set(CMAKE_INSTALL_PREFIX /opt/cheerp CACHE STRING "")
set(CHEERP_PREFIX ${CMAKE_INSTALL_PREFIX} CACHE STRING "")

SET(LLVM_ENABLE_RUNTIMES "libcxx;libcxxabi" CACHE STRING "")


set(CMAKE_MODULE_PATH "${CHEERP_PREFIX}/share/cmake/Modules" CACHE STRING "")
set(LIBCXX_ENABLE_SHARED OFF CACHE BOOL "")
set(LIBCXX_ENABLE_ASSERTIONS OFF CACHE BOOL "")
set(LIBCXX_INCLUDE_BENCHMARKS OFF CACHE BOOL "")
set(LIBCXX_ENABLE_ABI_LINKER_SCRIPT OFF CACHE BOOL "")
set(LIBCXX_LINK_TESTS_WITH_SHARED_LIBCXX OFF CACHE BOOL "")
set(LIBCXX_HAS_MUSL_LIBC ON CACHE BOOL "")
set(LIBCXXABI_ENABLE_SHARED OFF CACHE BOOL "")
set(LIBCXXABI_ENABLE_ASSERTIONS OFF CACHE BOOL "")
set(LIBCXXABI_ENABLE_THREADS OFF CACHE BOOL "")
set(LIBCXXABI_LINK_TESTS_WITH_SHARED_LIBCXX OFF CACHE BOOL "")
set(LIBCXXABI_LINK_TESTS_WITH_SHARED_LIBCXXABI OFF CACHE BOOL "")
set(LIBCXX_ENABLE_NEW_DELETE_DEFINITIONS ON CACHE BOOL "")
set(CMAKE_C_COMPILER "${CHEERP_PREFIX}/bin/clang" CACHE STRING "")
set(CMAKE_CXX_COMPILER "${CHEERP_PREFIX}/bin/clang++" CACHE STRING "")
set(CMAKE_LINKER "${CHEERP_PREFIX}/bin/llvm-link" CACHE STRING "")
set(CMAKE_SYSTEM_NAME "Cheerp" CACHE INTERNAL "")

